app = "ezgear"
primary_region = "syd"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ["app"]

[mounts]
  source="ezgear_data"
  destination="/app/uploads"